### ISSUE TITLE
Bug in test with Stack-questions

### ISSUE THREAD

**Issue by lauener** [ilub-unibe-ch/assStackQuestion#1]
I can reproduce the bug from Kinga.

1) I copied her test in this area
https://ilias.unibe.ch/goto_ilias3_unibe_crs_2877510.html

2) I start the test with my testuser h.lauener2, then I finish the test - and click Continue

3) As a admin of the test, I don`t the "h.lauener2" in the Dashboard of the test, but the "Results" are empty

**Comment by lauener** [comment]
When I start the test a second time, and I fill out question nr. 7, and finish the test, then I see the results. In the test-results, I see that the pass1 is not scored.
![Bildschirmfoto 2023-10-09 um 08 54 26](https://github.com/ilub-unibe-ch/assStackQuestion/assets/1730109/605463c2-fc53-4a93-9ef0-9834a55822b7)

**Comment by okaufman** [comment]
now this problem no longer occurs. I close this issue
